### ISSUE TITLE
Фикс

### ISSUE THREAD

**Issue by martinkomitsky** [Guiltlessness/2018-FS-11-Frontend-Boldyrev#3]
default export должен быть только один. Если нужно экспортить что-то еще, помимо дефолтного значения, то тогда надо писать просто, например, export KB;
но в данном случае, эти экспорты не знаю, зачем тебе нужны) я бы их убрал

https://github.com/Guiltlessness/2018-FS11-Frontend-Boldyrev/pull/2/files/adb7b547cc86db77ee8f6b4880e5717fd6080fa3#diff-02833eb1af67c37e954daeef7f0f6533

**Comment by Guiltlessness** [comment]
Я вас понял. Я сас не знаю зачем мне эти значения. Это просто в задании указано.

**Comment by martinkomitsky** [comment]
OK!
А поменяй, пожалуйста, название репозитория, чтобы между FS и 11 был дефис: "FS-11". Ты у меня на почту не попадаешь в нужное место от фильтра.

**Comment by Guiltlessness** [comment]
Done
